POSTGRES_URL="postgres-server-mlt.postgres.database.azure.com"  #TODO: Update value
POSTGRES_USER="azureuser@postgres-server-mlt" #TODO: Update value
POSTGRES_PW=""   #TODO: Update value
POSTGRES_DB="techconfdb"   #TODO: Update value
SERVICE_BUS_CONNECTION_STRING ='' #TODO: Update value
SERVICE_BUS_QUEUE_NAME ='notificationqueue'
ADMIN_EMAIL_ADDRESS = 'mailetoan@gmail.com'
GMAIL_USER = ''
GMAIL_PASSWORD = ''